data:extend(
{
  {
    type = "item-group",
    name = "Letters",
    icon = "__Letters__/graphics/letter/abc.png",
    inventory_order = "z",
    order = "z"
  },
  {
    type = "item-subgroup",
    name = "Silver",
    group = "Letters",
    order = "a",
  },
  {
    type = "technology",
    name = "Letters",
    icon = "__Letters__/graphics/letter/abc.png",
    effects = {
      {type = "unlock-recipe",recipe = "letter-uc-a"},
	  {type = "unlock-recipe",recipe = "letter-uc-b"},
	  {type = "unlock-recipe",recipe = "letter-uc-c"},
	  {type = "unlock-recipe",recipe = "letter-uc-d"},
	  {type = "unlock-recipe",recipe = "letter-uc-e"},
	  {type = "unlock-recipe",recipe = "letter-uc-f"},
	  {type = "unlock-recipe",recipe = "letter-uc-g"},
	  {type = "unlock-recipe",recipe = "letter-uc-h"},
	  {type = "unlock-recipe",recipe = "letter-uc-i"},
	  {type = "unlock-recipe",recipe = "letter-uc-j"},
	  {type = "unlock-recipe",recipe = "letter-uc-k"},
	  {type = "unlock-recipe",recipe = "letter-uc-l"},
	  {type = "unlock-recipe",recipe = "letter-uc-m"},
	  {type = "unlock-recipe",recipe = "letter-uc-n"},
	  {type = "unlock-recipe",recipe = "letter-uc-o"},
	  {type = "unlock-recipe",recipe = "letter-uc-p"},
	  {type = "unlock-recipe",recipe = "letter-uc-q"},
	  {type = "unlock-recipe",recipe = "letter-uc-r"},
	  {type = "unlock-recipe",recipe = "letter-uc-s"},
	  {type = "unlock-recipe",recipe = "letter-uc-t"},
	  {type = "unlock-recipe",recipe = "letter-uc-u"},
	  {type = "unlock-recipe",recipe = "letter-uc-v"},
	  {type = "unlock-recipe",recipe = "letter-uc-w"},
	  {type = "unlock-recipe",recipe = "letter-uc-x"},
	  {type = "unlock-recipe",recipe = "letter-uc-y"},
	  {type = "unlock-recipe",recipe = "letter-uc-z"},
	  {type = "unlock-recipe",recipe = "letter-lc-a"},
	  {type = "unlock-recipe",recipe = "letter-lc-b"},
	  {type = "unlock-recipe",recipe = "letter-lc-c"},
	  {type = "unlock-recipe",recipe = "letter-lc-d"},
	  {type = "unlock-recipe",recipe = "letter-lc-e"},
	  {type = "unlock-recipe",recipe = "letter-lc-f"},
	  {type = "unlock-recipe",recipe = "letter-lc-g"},
	  {type = "unlock-recipe",recipe = "letter-lc-h"},
	  {type = "unlock-recipe",recipe = "letter-lc-i"},
	  {type = "unlock-recipe",recipe = "letter-lc-j"},
	  {type = "unlock-recipe",recipe = "letter-lc-k"},
	  {type = "unlock-recipe",recipe = "letter-lc-l"},
	  {type = "unlock-recipe",recipe = "letter-lc-m"},
	  {type = "unlock-recipe",recipe = "letter-lc-n"},
	  {type = "unlock-recipe",recipe = "letter-lc-o"},
	  {type = "unlock-recipe",recipe = "letter-lc-p"},
	  {type = "unlock-recipe",recipe = "letter-lc-q"},
	  {type = "unlock-recipe",recipe = "letter-lc-r"},
	  {type = "unlock-recipe",recipe = "letter-lc-s"},
	  {type = "unlock-recipe",recipe = "letter-lc-t"},
	  {type = "unlock-recipe",recipe = "letter-lc-u"},
	  {type = "unlock-recipe",recipe = "letter-lc-v"},
	  {type = "unlock-recipe",recipe = "letter-lc-w"},
	  {type = "unlock-recipe",recipe = "letter-lc-x"},
	  {type = "unlock-recipe",recipe = "letter-lc-y"},
	  {type = "unlock-recipe",recipe = "letter-lc-z"},
	  {type = "unlock-recipe",recipe = "letter-s-0"},
	  {type = "unlock-recipe",recipe = "letter-s-1"},
	  {type = "unlock-recipe",recipe = "letter-s-2"},
	  {type = "unlock-recipe",recipe = "letter-s-3"},
	  {type = "unlock-recipe",recipe = "letter-s-4"},
	  {type = "unlock-recipe",recipe = "letter-s-5"},
	  {type = "unlock-recipe",recipe = "letter-s-6"},
	  {type = "unlock-recipe",recipe = "letter-s-7"},
	  {type = "unlock-recipe",recipe = "letter-s-8"},
	  {type = "unlock-recipe",recipe = "letter-s-9"},
	  {type = "unlock-recipe",recipe = "letter-s-and"},
	  {type = "unlock-recipe",recipe = "letter-s-equal"},
	  {type = "unlock-recipe",recipe = "letter-s-exclamation"},
	  {type = "unlock-recipe",recipe = "letter-s-op"},
	  {type = "unlock-recipe",recipe = "letter-s-plate"},
	  {type = "unlock-recipe",recipe = "letter-s-plus"},
	  {type = "unlock-recipe",recipe = "letter-s-question"},
	  {type = "unlock-recipe",recipe = "letter-s-slash"}
	  },
    unit =
    {
      count = 10,
      ingredients =
      {
        {"science-pack-1", 1}
      },
      time = 5
    },
    order = "i-a"
  }

})