data:extend(
{
	{
     type = "decorative",
     name = "letter-uc-a",
     icon = "__Letters__/graphics/letter/ua.png",
	 pictures = {{filename = "__Letters__/graphics/letter/ua.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[aa]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-uc-b",
     icon = "__Letters__/graphics/letter/ub.png",
	 pictures = {{filename = "__Letters__/graphics/letter/ub.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[ab]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-uc-c",
     icon = "__Letters__/graphics/letter/uc.png",
	 pictures = {{filename = "__Letters__/graphics/letter/uc.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[ac]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-uc-d",
     icon = "__Letters__/graphics/letter/ud.png",
	 pictures = {{filename = "__Letters__/graphics/letter/ud.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[ad]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-uc-e",
     icon = "__Letters__/graphics/letter/ue.png",
	 pictures = {{filename = "__Letters__/graphics/letter/ue.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[ae]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-uc-f",
     icon = "__Letters__/graphics/letter/uf.png",
	 pictures = {{filename = "__Letters__/graphics/letter/uf.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[af]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-uc-g",
     icon = "__Letters__/graphics/letter/ug.png",
	 pictures = {{filename = "__Letters__/graphics/letter/ug.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[a]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-uc-h",
     icon = "__Letters__/graphics/letter/uh.png",
	 pictures = {{filename = "__Letters__/graphics/letter/uh.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[ah]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-uc-i",
     icon = "__Letters__/graphics/letter/ui.png",
	 pictures = {{filename = "__Letters__/graphics/letter/ui.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[ai]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-uc-j",
     icon = "__Letters__/graphics/letter/uj.png",
	 pictures = {{filename = "__Letters__/graphics/letter/uj.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[aj]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-uc-k",
     icon = "__Letters__/graphics/letter/uk.png",
	 pictures = {{filename = "__Letters__/graphics/letter/uk.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[ak]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-uc-l",
     icon = "__Letters__/graphics/letter/ul.png",
	 pictures = {{filename = "__Letters__/graphics/letter/ul.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[al]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-uc-m",
     icon = "__Letters__/graphics/letter/um.png",
	 pictures = {{filename = "__Letters__/graphics/letter/um.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[am]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-uc-n",
     icon = "__Letters__/graphics/letter/un.png",
	 pictures = {{filename = "__Letters__/graphics/letter/un.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[an]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-uc-o",
     icon = "__Letters__/graphics/letter/uo.png",
	 pictures = {{filename = "__Letters__/graphics/letter/uo.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[ao]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-uc-p",
     icon = "__Letters__/graphics/letter/up.png",
	 pictures = {{filename = "__Letters__/graphics/letter/up.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[ap]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-uc-q",
     icon = "__Letters__/graphics/letter/uq.png",
	 pictures = {{filename = "__Letters__/graphics/letter/uq.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[aq]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-uc-r",
     icon = "__Letters__/graphics/letter/ur.png",
	 pictures = {{filename = "__Letters__/graphics/letter/ur.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[ar]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-uc-s",
     icon = "__Letters__/graphics/letter/us.png",
	 pictures = {{filename = "__Letters__/graphics/letter/us.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[as]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-uc-t",
     icon = "__Letters__/graphics/letter/ut.png",
	 pictures = {{filename = "__Letters__/graphics/letter/ut.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[at]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-uc-u",
     icon = "__Letters__/graphics/letter/uu.png",
	 pictures = {{filename = "__Letters__/graphics/letter/uu.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[a]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-uc-v",
     icon = "__Letters__/graphics/letter/uv.png",
	 pictures = {{filename = "__Letters__/graphics/letter/uv.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[av]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-uc-w",
     icon = "__Letters__/graphics/letter/uw.png",
	 pictures = {{filename = "__Letters__/graphics/letter/uw.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[aw]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-uc-x",
     icon = "__Letters__/graphics/letter/ux.png",
	 pictures = {{filename = "__Letters__/graphics/letter/ux.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[ax]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-uc-y",
     icon = "__Letters__/graphics/letter/uy.png",
	 pictures = {{filename = "__Letters__/graphics/letter/uy.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[ay]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-uc-z",
     icon = "__Letters__/graphics/letter/uz.png",
	 pictures = {{filename = "__Letters__/graphics/letter/uz.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[az]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-lc-a",
     icon = "__Letters__/graphics/letter/la.png",
	 pictures = {{filename = "__Letters__/graphics/letter/la.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[ca]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-lc-b",
     icon = "__Letters__/graphics/letter/lb.png",
	 pictures = {{filename = "__Letters__/graphics/letter/lb.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[cb]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-lc-c",
     icon = "__Letters__/graphics/letter/lc.png",
	 pictures = {{filename = "__Letters__/graphics/letter/lc.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[cc]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-lc-d",
     icon = "__Letters__/graphics/letter/ld.png",
	 pictures = {{filename = "__Letters__/graphics/letter/ld.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[cd]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-lc-e",
     icon = "__Letters__/graphics/letter/le.png",
	 pictures = {{filename = "__Letters__/graphics/letter/le.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[ce]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-lc-f",
     icon = "__Letters__/graphics/letter/lf.png",
	 pictures = {{filename = "__Letters__/graphics/letter/lf.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[cf]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-lc-g",
     icon = "__Letters__/graphics/letter/lg.png",
	 pictures = {{filename = "__Letters__/graphics/letter/lg.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[c]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-lc-h",
     icon = "__Letters__/graphics/letter/lh.png",
	 pictures = {{filename = "__Letters__/graphics/letter/lh.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[ch]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-lc-i",
     icon = "__Letters__/graphics/letter/li.png",
	 pictures = {{filename = "__Letters__/graphics/letter/li.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[ci]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-lc-j",
     icon = "__Letters__/graphics/letter/lj.png",
	 pictures = {{filename = "__Letters__/graphics/letter/lj.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[cj]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-lc-k",
     icon = "__Letters__/graphics/letter/lk.png",
	 pictures = {{filename = "__Letters__/graphics/letter/lk.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[ck]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-lc-l",
     icon = "__Letters__/graphics/letter/ll.png",
	 pictures = {{filename = "__Letters__/graphics/letter/ll.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[cl]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-lc-m",
     icon = "__Letters__/graphics/letter/lm.png",
	 pictures = {{filename = "__Letters__/graphics/letter/lm.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[cm]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-lc-n",
     icon = "__Letters__/graphics/letter/ln.png",
	 pictures = {{filename = "__Letters__/graphics/letter/ln.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[cn]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-lc-o",
     icon = "__Letters__/graphics/letter/lo.png",
	 pictures = {{filename = "__Letters__/graphics/letter/lo.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[co]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-lc-p",
     icon = "__Letters__/graphics/letter/lp.png",
	 pictures = {{filename = "__Letters__/graphics/letter/lp.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[cp]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-lc-q",
     icon = "__Letters__/graphics/letter/lq.png",
	 pictures = {{filename = "__Letters__/graphics/letter/lq.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[cq]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-lc-r",
     icon = "__Letters__/graphics/letter/lr.png",
	 pictures = {{filename = "__Letters__/graphics/letter/lr.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[cr]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-lc-s",
     icon = "__Letters__/graphics/letter/ls.png",
	 pictures = {{filename = "__Letters__/graphics/letter/ls.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[cs]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-lc-t",
     icon = "__Letters__/graphics/letter/lt.png",
	 pictures = {{filename = "__Letters__/graphics/letter/lt.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[ct]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-lc-u",
     icon = "__Letters__/graphics/letter/lu.png",
	 pictures = {{filename = "__Letters__/graphics/letter/lu.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[c]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-lc-v",
     icon = "__Letters__/graphics/letter/lv.png",
	 pictures = {{filename = "__Letters__/graphics/letter/lv.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[cv]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-lc-w",
     icon = "__Letters__/graphics/letter/lw.png",
	 pictures = {{filename = "__Letters__/graphics/letter/lw.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[cw]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-lc-x",
     icon = "__Letters__/graphics/letter/lx.png",
	 pictures = {{filename = "__Letters__/graphics/letter/lx.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[cx]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-lc-y",
     icon = "__Letters__/graphics/letter/ly.png",
	 pictures = {{filename = "__Letters__/graphics/letter/ly.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[cy]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-lc-z",
     icon = "__Letters__/graphics/letter/lz.png",
	 pictures = {{filename = "__Letters__/graphics/letter/lz.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[cz]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-s-0",
     icon = "__Letters__/graphics/letter/0.png",
	 pictures = {{filename = "__Letters__/graphics/letter/0.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[da]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-s-1",
     icon = "__Letters__/graphics/letter/1.png",
	 pictures = {{filename = "__Letters__/graphics/letter/1.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[db]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-s-2",
     icon = "__Letters__/graphics/letter/2.png",
	 pictures = {{filename = "__Letters__/graphics/letter/2.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[dc]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-s-3",
     icon = "__Letters__/graphics/letter/3.png",
	 pictures = {{filename = "__Letters__/graphics/letter/3.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[dd]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-s-4",
     icon = "__Letters__/graphics/letter/4.png",
	 pictures = {{filename = "__Letters__/graphics/letter/4.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[de]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-s-5",
     icon = "__Letters__/graphics/letter/5.png",
	 pictures = {{filename = "__Letters__/graphics/letter/5.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[df]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-s-6",
     icon = "__Letters__/graphics/letter/6.png",
	 pictures = {{filename = "__Letters__/graphics/letter/6.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[dg]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-s-7",
     icon = "__Letters__/graphics/letter/7.png",
	 pictures = {{filename = "__Letters__/graphics/letter/7.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[dh]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-s-8",
     icon = "__Letters__/graphics/letter/8.png",
	 pictures = {{filename = "__Letters__/graphics/letter/8.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[di]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-s-9",
     icon = "__Letters__/graphics/letter/9.png",
	 pictures = {{filename = "__Letters__/graphics/letter/9.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[dj]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-s-and",
     icon = "__Letters__/graphics/letter/and.png",
	 pictures = {{filename = "__Letters__/graphics/letter/and.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[dk]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-s-equal",
     icon = "__Letters__/graphics/letter/equal.png",
	 pictures = {{filename = "__Letters__/graphics/letter/equal.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[dl]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-s-exclamation",
     icon = "__Letters__/graphics/letter/exclamation.png",
	 pictures = {{filename = "__Letters__/graphics/letter/exclamation.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[dm]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-s-op",
     icon = "__Letters__/graphics/letter/op.png",
	 pictures = {{filename = "__Letters__/graphics/letter/op.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[dn]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-s-plate",
     icon = "__Letters__/graphics/letter/plate.png",
	 pictures = {{filename = "__Letters__/graphics/letter/plate.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[do]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-s-plus",
     icon = "__Letters__/graphics/letter/plus.png",
	 pictures = {{filename = "__Letters__/graphics/letter/plus.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[dp]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-s-question",
     icon = "__Letters__/graphics/letter/question.png",
	 pictures = {{filename = "__Letters__/graphics/letter/question.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[dq]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	},
	{
     type = "decorative",
     name = "letter-s-slash",
     icon = "__Letters__/graphics/letter/slash.png",
	 pictures = {{filename = "__Letters__/graphics/letter/slash.png",width = 32,height = 32}},
     order = "b[decorative]-a[Silver]-a[dr]",
	 flags = {"placeable-neutral", "placeable-off-grid"},
     collision_box = {{0, 0}, {0, 0}},
     selection_box = {{-0.5, -0.5}, {0.5, 0.5}},
	 minable = {hardness = 0.5, mining_time = 0.3, result = "wood"}
	}
})


